version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: backend
    volumes:
      - ./src:/app/src
    command: ./gradlew run

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # frontend no navegador via localhost:3000
    container_name: frontend
    depends_on:
      - backend
